[package]
name = "rust-sorting-algorithms"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
rand = "0.8.4"
criterion = "0.3.5"
arr_macro = "0.1.3"

[[bench]]
name = "benchmarks"
harness = false